### ISSUE TITLE
Browser's console logging

### ISSUE THREAD

**Issue by ingmferrer** [deakjahn/sqflite_web#10]
Hello,

This plugin is working as expected, no problem on that but I see it is leaving prints in the browser console:

For example:
`INSERT OR REPLACE INTO gender (id, name, icon) VALUES (?, ?, ?) [2, Femenino, venus]`

Is there a way to stop logging the "database" transactions in the browser console?

Thanks.

**Comment by deakjahn** [comment]
Indeed. I wonder if this should somehow be passed in when opening.
