### ISSUE TITLE
Is the database persisted on disk among visits to my website?

### ISSUE THREAD

**Issue by mzimbres** [deakjahn/sqflite_web#11]
Hi, will this plugin allow me to persist session data in the disk that can be accessed each time the user accesses my website? This is not clear to me as sql.js states the following:  _It uses a virtual database file stored in memory, and thus doesn't persist the changes made to the database_.

**Comment by deakjahn** [comment]
No, it isn't persisted. This is the main reason why this is only a test project here and not something fully embraced by Sqflite itself. It would be possible to persist manually when you're done using the database but it isn't automatic and it doesn't ensure that, if you happen to have the same app running in two instances in two browser tabs, to see a consistent common database.

**Comment by mzimbres** [comment]
Thanks for clarifying.
