### ISSUE TITLE
Open from existing database

### ISSUE THREAD

**Issue by ErliSoares** [deakjahn/sqflite_web#14]
Is it possible to open an existing database?

I made some changes to the project to test, exposing the method below it works, but I was unable to access it from outside the library.

https://github.com/deakjahn/sqflite_web/blob/8a3dee8f795a492bf0498ecf3fddb884d917dab4/lib/src/sqflite_web_impl.dart#L95-L103

**Comment by QuentinCG** [comment]
Hello,
I'm not the maintainer of this project but I think what you want to access is a private function that can't be accessed from the "ffi" logic (interface).
Note: You'll see that no override is provided for this function.

Factory for sqflite common:
https://pub.dev/documentation/sqflite_common/latest/sqlite_api/DatabaseFactory-class.html


Database class usable functions: https://pub.dev/documentation/sqflite_common/latest/sqlite_api/Database-class.html 


Maybe there is a way to achieve what you want but you'll need to explicitly call the web class without using the interface.
Maybe the maintainer knows how to do this...

**Comment by deakjahn** [comment]
`DatabaseFactoryWeb` has a path-based `openDatabase()` but I see no problem at all adding a similar function there that calls the `SqfliteWebDatabase.fromData()` constructor instead of the default one.

**Comment by yoniker** [comment]
This issue has been open for quite a long time..
Currently is there a way to open an existing sqlite3 database from assets?
If so it would be awesome to have a small example of how to do that.

**Comment by deakjahn** [comment]
I don't have your database to test it with but Sqflite's `DatabaseFactory` doesn't have such a variant of its `openDatabase()`. Still, you can add one easily and call the function mentioned in the first post. If you don't need to stay compatible with the other platform versions, it's easy to do.

I'd say something like that:

    Future<Database> openDatabaseData(String path, Uint8List data, {OpenDatabaseOptions? options}) async {
      await SqflitePluginWeb.isReady;
      return _db ??= SqfliteWebDatabase.fromData(path: path, readOnly: false, logLevel: sqfliteLogLevelNone, data: data);
    }

and calling it:

    var db = await (databaseFactory as DatabaseFactoryWeb).openDatabaseData(inMemoryDatabasePath, ...);

But, as you can see, you will need to cast to the exact type because the abstract class doesn't have this method.

**Comment by deakjahn** [comment]
You may want to try this small modification, the example has a commented out section now.

https://github.com/deakjahn/sqflite_web/commit/fa4cddcea69a1c5959e92628ca697894c65fe614

**Comment by BlackFireAlex** [comment]
I'd be great to be able to open a DB from Uint8List. Because for now it's impossible to open a database from URL in the web version.
