### ISSUE TITLE
The  OpenDatabaseOptions not works

### ISSUE THREAD

**Issue by omidraha** [deakjahn/sqflite_web#16]
Also in the `generated_plugin_registrant.dart` generated file.

I got this error:

```
Undefined name 'SqflitePluginWeb'.
```

```dart
//
// Generated file. Do not edit.
//

// ignore_for_file: lines_longer_than_80_chars

import 'package:sqflite_web/sqflite_web.dart';
// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
...
  SqflitePluginWeb.registerWith(registrar);
...
}

```

Pubspec.yaml

```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  sqlite3_flutter_libs: ^0.5.0
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: master

```

main.dart
```dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';
import 'package:sqflite_web/sqflite_web.dart';


Future onConfigure(Database db) async {
  await db.execute('PRAGMA foreign_keys = ON');
}

Future<Database> database() async {
  var databaseFactory;
  if (kIsWeb) {
    databaseFactory = databaseFactoryWeb;
  } else if (Platform.isWindows || Platform.isLinux) {
    sqfliteFfiInit();
    databaseFactory = databaseFactoryFfi;
  }
  final Future<Database> database = databaseFactory.openDatabase(
    kIsWeb
        ? inMemoryDatabasePath
        : join(await getDatabasesPath(), 'database.db'),
    options: OpenDatabaseOptions(
      onConfigure: onConfigure,
      onCreate: (db, version) async {
        print(' ******** Never run  ********');
        Batch batch = db.batch();
        createTables(batch);
        createIndexes(batch);
        await batch.commit(continueOnError: false);
      },
      version: 1,
    ),
  );
  return database;
}

```

Traceback
```
Error: no such table: user

```

It seems the `OpenDatabaseOptions' or `onCreate` of `OpenDatabaseOptions'  not works.

And Also it seems `batch` commit is not works:

```dart
    await db.setVersion(1);
    Batch batch = db.batch();
    batch.execute("CREATE TABLE User");
    await batch.commit();
```

Traceback:
```
Error: Expected a value of type 'List<dynamic>', but got one of type 'Null'
```

**Comment by deakjahn** [comment]
No, I don't think I ever paid any attention to those options. Are they important? Considering that, as the docs describe--and this is the reason why the main Sqflite branch never really endorsed the web--, there's no persistency to start with.

As I can see, most of the options (update and similar) have no purpose unless the database is actually persisted...

**Comment by ekuleshov** [comment]
> As I can see, most of the options (update and similar) have no purpose unless the database is actually persisted...

Perhaps not the `onUpgrade`, but the `version` and `onCreate` are normally used to init the database structure. E.g. the following lines from this project example do belong to the 
`OpenDatabaseOptions.version` and `OpenDatabaseOptions.onCreate` params and would provide basic compatibility with non-web api.

https://github.com/deakjahn/sqflite_web/blob/5e394d2664e88cc9249b4f64da93e6dd2b715048/example/lib/main.dart#L14-L23

**Comment by deakjahn** [comment]
I lost track of what's really needed here, I haven't used it for some time myself. :-) Could you make a broader suggestion, of maybe even a PR?

**Comment by ekuleshov** [comment]
Sure. Normally the `openDatabase` is called like this with a regular `sqflite`, so the `onCreate` callback is automatically called when db is not initialized.

I guess the `sqflite_web` can just unconditionally set the `version` and call `onCreate` on the `openDatabase` call and ignore all other callbacks from the passed in `OpenDatabaseOptions` instance.

```
    Database db = await f.openDatabase(path,
        options: OpenDatabaseOptions(
          version: 10,
          onCreate: (Database db, int version) async {
            await db.execute(''' 
              CREATE TABLE Product ( 
                id INTEGER PRIMARY KEY, 
                title TEXT 
              ) 
              '''); 
          },
       ),
    );
```

**Comment by deakjahn** [comment]
I start to see. The problem is that we don't call these callbacks, is it?

Perhaps something as simple as:

```dart
@override
Future<Database> openDatabase(String path, {OpenDatabaseOptions? options}) async {
  await SqflitePluginWeb.isReady;
  _db ??= SqfliteWebDatabase(path: path, readOnly: options?.readOnly ?? false, logLevel: sqfliteLogLevelNone);
  options?.onConfigure?.call(_db!);
  options?.onCreate?.call(_db!, options.version ?? 0);
  options?.onOpen?.call(_db!);
  return _db!;
}

/// Load a database from byte data
Future<Database> loadDatabase(Uint8List data, {OpenDatabaseOptions? options}) async {
  await SqflitePluginWeb.isReady;
  _db ??= SqfliteWebDatabase.fromData(readOnly: options?.readOnly ?? false, logLevel: sqfliteLogLevelNone, data: data);
  options?.onConfigure?.call(_db!);
  options?.onCreate?.call(_db!, options.version ?? 0);
  options?.onOpen?.call(_db!);
  return _db!;
}
```

**Comment by deakjahn** [comment]
Let's see if this solves it. My initial tests seem to work OK.

**Comment by ekuleshov** [comment]
Thank you. I will give it a try.

**Comment by MurtuzaSrashtaSoft** [comment]
`await SqflitePluginWeb.isReady;
`
compiler not able to execute after this line code.

so not able to create database instance .

versions derail

` sqflite: ^2.0.2+1`

```
  sqflite_web:
    git:
      url: https://github.com/deakjahn/sqflite_web.git
      ref: master
```

**Comment by deakjahn** [comment]
Considering that Alex (the author of the main `sqflite` package) is currently working on a modern web version that will probably be part of the original package soon, I have a feeling that this package will become deprecated and obsolete soon. :-)

**Comment by MurtuzaSrashtaSoft** [comment]
@deakjahn Thank for update i see [alextekartik](https://github.com/alextekartik) working on web experiment.
