### ISSUE TITLE
Not able to add dependency.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [deakjahn/sqflite_web#23]
../../Library/Android/flutter/.pub-cache/git/sqflite_web-5e394d2664e88cc9249b4f64da93e6dd2b715048/lib/src/sqflite_web_impl.dart:5:8: Error: Not found: 'dart:js'

../../Library/Android/flutter/.pub-cache/git/sqflite_web-5e394d2664e88cc9249b4f64da93e6dd2b715048/lib/src/sqflite_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
![Screenshot 2022-01-31 at 10 23 57 PM](https://user-images.githubusercontent.com/64843262/151837471-01fdeba0-3872-4b6a-bd75-b87efa1c8563.png)

**Comment by deakjahn** [comment]
This will be an error in your dev environment. At any rate, I won't be able to even test it without a reproducible sample. The current plugin, with the example inside, compiles and runs perfectly for me.

**Comment by MurtuzaSrashtaSoft** [comment]
@deakjahn Thank for update i see [alextekartik](https://github.com/alextekartik) working on web experiment.
