### ISSUE TITLE
No transaction support

### ISSUE THREAD

**Issue by jonsutherland** [deakjahn/sqflite_web#8]
Currently my application crashes due to no transaction support:
![image](https://user-images.githubusercontent.com/884351/87049701-e0b04800-c1d7-11ea-8072-4bd09deda5a2.png)

Any plans to support this?  sql-js seems to support it.  Anything preventing it?  

Perhaps a PR with support would be okay if possible?

**Comment by deakjahn** [comment]
I didn't realize it, probably, I simply used this: https://sql-js.github.io/sql.js/documentation/class/Database.html

If it's possible, no reason not to support it, PR or otherwise. But I can't see anything similar in that documentation. Can you?

**Comment by jonsutherland** [comment]
Rather than rewrite the db logic in the app I'm working on I might attempt to add some transaction support in your lib.  I'll report back if I have any success.  Thanks!

**Comment by deakjahn** [comment]
Sqflite itself has the proper support, the only problem is that I couldn't find any docs about transactions actually being supported in sql-js...

**Comment by jonsutherland** [comment]
Right, yeah.  
When I looked through issues I found this, which seems promising but I'm not sure either: 
https://github.com/sql-js/sql.js/issues/116#issuecomment-260555176

**Comment by deakjahn** [comment]
That might mean that there are no separate calls in the API, just using SQL itself to make the transaction. Well, possible. I actually never needed to do it that way, all frontends I ever used (including Sqflite) handled it for me, but they might very well just use the same in the background, come to think of it. I'll make a few tests to see.

**Comment by deakjahn** [comment]
@jonsutherland The wheel has already been invented, so I simply copied some parts from Alex to add the various bits and pieces required. First simple run is successful but now the fun begins. It should be tested to be successful, to be erroneous, to force rollback, and all that jazz.

**Comment by jonsutherland** [comment]
@deakjahn It's coming along with your latest commit.  Here is the latest error, it seems it's getting as far as committing the transaction at the end of my db code now! 
```
errors.dart:165 Uncaught (in promise) Error: UnimplementedError
    at Object.throw_ [as throw] (errors.dart:214)
    at sqflite_web_impl.SqfliteWebDatabase.new.txnApplyBatch (sqflite_web_impl.dart:472)
    at batch.SqfliteTransactionBatch.new.commit (batch.dart:149)
```
If that one can be implemented, I think we may have basic support for transactions. 👍

**Comment by deakjahn** [comment]
I was afraid we would need batches as well. :-) Could you come up with a very simple set of db operations that demonstrate this error? Something like the current ones in `main.dart`.

**Comment by jonsutherland** [comment]
Sure no problem.  For the most simplistic example:

```
 await db.transaction((txn) async {
      Batch batch = txn.batch();
      batch.rawInsert('INSERT INTO Product(title) VALUES(?)', ['Product 4']);
      batch.rawInsert('INSERT INTO Product(title) VALUES(?)', ['Product 5']);
      batch.commit();
  });
```

Let me know if that's too simple sorry!

**Comment by deakjahn** [comment]
Very rudimentary, not handling errors and `continueOnError` at all and I'm absolutely not convinced that this is the way to go forward with this. It would be nice to have @alextekartik Alex to say something about it. Transactions are handled by the engine all right but batches, I don't really know. Lots of error handling and other edge cases should be observed here, I'm afraid.

**Comment by jonsutherland** [comment]
@deakjahn at least the rudimentary implementation now works okay with my application code with transactions and batches.  So it's a good start, but I understand it's not any way complete at the moment.  Thanks for the changes so far

**Comment by deakjahn** [comment]
Until you run into errors. :-) We'll see what Alex thinks.

**Comment by alextekartik** [comment]
Batches are very important on the native side. It avoids a lot of data exchange using flutter services which are very expensive (event if you do 1000 inserts in a transaction). This is very similar to the concept of batch in android providers; https://developer.android.com/guide/topics/providers/content-provider-basics#Batch

Sorry the data format exchanged between the dart and native side in sqflite is not documented but basically the query is a list of commands instead of a single one and the response is a list of results (being a count, an id or map list depending on the operation done).

The normal behavior is to cancel the transaction if an operation failed. continueOnError was added after a feature request (personally I don't use it as I want to know if an operation fail or not, but well some people are using it).

Unfortunately, as @deakjahn started, batch support has to be implemented on the native side. sqflite has a bunch of [unit tests](https://github.com/tekartik/sqflite/blob/master/sqflite_common_test/lib/batch_test.dart) on this that unfortunately are not compatible with flutter_web (but could easily be ported using in memory databases).

**Comment by deakjahn** [comment]
On native, you have everything set up practically as commands and sent through the channels. But is it important here where it can be executed directly? Or is it simply enough to treat batch as simply calling the statements one by one, as it is right now?

**Comment by alextekartik** [comment]
In sqflite/ffi, it is different as commands are executed in a background thread/isolates which makes it slightly more complex. AFAIK sqflite_web executes everything in the main isolate so calling statements one by one looks fine to me.

**Comment by deakjahn** [comment]
Then I'll only have to think about whether to do error handling and how to do it.

Actually, there may come a time when we can compile Dart to JS into a separate file, not the main one, and then we'll be able to use web workers as isolates...
