### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ingmferrer** [deakjahn/sqflite_web#9]
Hello, 

I'm not sure how to install this plugin in my flutter web project.

Sorry for the dumb question.

**Comment by deakjahn** [comment]
You copy it among your other projects and in your `pubspec.yaml` file you can refer to it with a slightly modified syntax to get it locally:

    sqflite_web:
      path: ../wherever/

You can find the [Flutter documentation](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages) here. You could actually also link to the GitHub version.
